/**
 * The service worker, from the page's side: whether the whole course is kept
 * on this device for offline use, and whether a new version is waiting.
 * The worker itself is generated by vite-plugin-pwa (vite.config.ts).
 *
 * Never reload under a learner (CLAUDE.md rule 2, docs/notes/phase-6.md):
 * - A new version installs in the background, then waits. The shell shows
 *   "A new version is ready" (UpdateBanner) and nothing changes until
 *   someone taps "Update now". Otherwise it starts the next time
 *   Thinkerwell opens with no tab still on the old version.
 * - Only the tab where "Update now" was tapped reloads. If another tab
 *   takes the update, this one keeps running and keeps offering it.
 *
 * Registered in production only (main.tsx), after the page has loaded, so
 * the precache download never competes with the first page's own files.
 * Everything here is a small external store read with
 * useSyncExternalStore; tests drive it through connectServiceWorker() with
 * a fake Workbox.
 */
import { useSyncExternalStore } from 'react';

/**
 * - 'unsupported': no service worker here (an old browser, plain http, some
 *   private windows, or the dev server), so the site needs the internet.
 * - 'checking': registering; not known yet.
 * - 'preparing': the first visit, downloading the course for offline use.
 * - 'ready': the whole course is on this device (a worker is active, which
 *   it only becomes once everything it precaches is stored).
 * - 'failed': the download didn't finish (the connection dropped). The
 *   browser tries again the next time Thinkerwell opens.
 */
export type OfflineStatus = 'unsupported' | 'checking' | 'preparing' | 'ready' | 'failed';

export interface ServiceWorkerSnapshot {
  offline: OfflineStatus;
  /** A new version is installed and waiting for someone to tap "Update now". */
  updateReady: boolean;
}

type LifecycleType = 'waiting' | 'activated' | 'controlling' | 'redundant';

/** The parts of workbox-window's Workbox used here (a fake in tests). */
export interface WorkboxLike {
  addEventListener(type: LifecycleType, listener: (event: { isExternal?: boolean }) => void): void;
  register(): Promise<ServiceWorkerRegistration | undefined>;
  update(): Promise<void>;
  messageSkipWaiting(): void;
}

export interface ServiceWorkerEnvironment {
  workbox: WorkboxLike;
  /** Whether a service worker controls this page right now. */
  isControlled: () => boolean;
  reload: () => void;
  isOnline: () => boolean;
  isVisible: () => boolean;
}

/** How often an open page asks whether there is a new version (when online and on screen). */
export const UPDATE_CHECK_MS = 60 * 60 * 1000;
/** After "Update now", reload anyway if the new version hasn't taken over by then. */
export const RELOAD_FALLBACK_MS = 4000;

const UNSUPPORTED: ServiceWorkerSnapshot = { offline: 'unsupported', updateReady: false };

let snapshot: ServiceWorkerSnapshot = UNSUPPORTED;
const listeners = new Set<() => void>();
let applyUpdate: () => void = () => undefined;

function setSnapshot(patch: Partial<ServiceWorkerSnapshot>): void {
  const next = { ...snapshot, ...patch };
  if (next.offline === snapshot.offline && next.updateReady === snapshot.updateReady) return;
  snapshot = next;
  listeners.forEach((listener) => listener());
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function getServiceWorkerSnapshot(): ServiceWorkerSnapshot {
  return snapshot;
}

/** The current offline status and whether a new version is waiting. Re-renders when either changes. */
export function useServiceWorker(): ServiceWorkerSnapshot {
  return useSyncExternalStore(subscribe, getServiceWorkerSnapshot, getServiceWorkerSnapshot);
}

/**
 * "Update now": lets the waiting version take over and reloads this tab
 * once it has (or at once, if another tab already switched to it).
 */
export function applyServiceWorkerUpdate(): void {
  applyUpdate();
}

/**
 * Wires the store to a Workbox. Returns a function that stops the periodic
 * update check (for tests). Exported for tests; the app calls
 * startServiceWorker().
 */
export function connectServiceWorker(env: ServiceWorkerEnvironment): () => void {
  const { workbox } = env;
  let registration: ServiceWorkerRegistration | undefined;
  let updateRequested = false;
  let controlled = env.isControlled();
  let fallback: ReturnType<typeof setTimeout> | undefined;

  // A page a worker already controls has the whole course: the worker only
  // became active once everything was stored.
  setSnapshot({ offline: controlled ? 'ready' : 'checking', updateReady: false });

  workbox.addEventListener('waiting', () => setSnapshot({ updateReady: true }));
  workbox.addEventListener('activated', () => setSnapshot({ offline: 'ready' }));
  workbox.addEventListener('redundant', (event) => {
    // Our own worker failed to install (the precache download broke off).
    if (!event.isExternal && snapshot.offline !== 'ready') setSnapshot({ offline: 'failed' });
  });
  workbox.addEventListener('controlling', () => {
    const wasControlled = controlled;
    controlled = true;
    if (updateRequested) {
      env.reload();
    } else if (wasControlled) {
      // Another tab took the update. This page still runs the old version
      // under the new worker: keep offering the reload, never force it.
      setSnapshot({ updateReady: true });
    }
    // Otherwise it is the first install taking charge of this page: nothing to do.
  });

  applyUpdate = () => {
    if (updateRequested) return;
    updateRequested = true;
    if (registration?.waiting) {
      workbox.messageSkipWaiting();
      fallback = setTimeout(env.reload, RELOAD_FALLBACK_MS);
    } else {
      env.reload();
    }
  };

  workbox.register().then(
    (result) => {
      registration = result;
      if (!result) {
        setSnapshot({ offline: 'unsupported' });
        return;
      }
      if (result.active) setSnapshot({ offline: 'ready' });
      else if (snapshot.offline === 'checking') setSnapshot({ offline: 'preparing' });
      if (result.waiting) setSnapshot({ updateReady: true });
    },
    () => setSnapshot({ offline: 'unsupported' }),
  );

  const timer = setInterval(() => {
    if (!registration || !env.isOnline() || !env.isVisible()) return;
    workbox.update().catch(() => undefined);
  }, UPDATE_CHECK_MS);

  return () => {
    clearInterval(timer);
    if (fallback) clearTimeout(fallback);
  };
}

/** For tests: back to "no service worker", with no listeners kept from a connect. */
export function resetServiceWorkerForTests(): void {
  snapshot = UNSUPPORTED;
  applyUpdate = () => undefined;
  listeners.forEach((listener) => listener());
}

/** Registers /sw.js (production only; main.tsx). Where there are no service workers, nothing happens. */
export function startServiceWorker(): void {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
  const container = navigator.serviceWorker;
  setSnapshot({ offline: container.controller ? 'ready' : 'checking' });
  import('workbox-window').then(
    ({ Workbox }) => {
      connectServiceWorker({
        workbox: new Workbox('/sw.js', { scope: '/' }),
        isControlled: () => Boolean(container.controller),
        reload: () => window.location.reload(),
        isOnline: () => navigator.onLine !== false,
        isVisible: () => document.visibilityState === 'visible',
      });
    },
    () => setSnapshot({ offline: 'unsupported' }),
  );
}
